apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: predictionservice
spec:
  type: ClusterIP
  selector:
    app: predictionservice
  ports:
  - name: api
    port: 80
    targetPort: api