apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: chronograf-ss
spec:
  clusterIP: None
  selector:
    app: chronograf
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: chronograf
spec:
  type: LoadBalancer
  selector:
    app: chronograf
  ports:
  - name: api
    port: 80
    targetPort: api