apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: kapacitor-ss
spec:
  clusterIP: None
  selector:
    app: kapacitor
  ports:
  - name: api
    port: 9092
    targetPort: api
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: kapacitor
spec:
  type: ClusterIP
  selector:
    app: kapacitor
  ports:
  - name: api
    port: 9092
    targetPort: api